import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import SignInRedirectClient from "@/components/SignInRedirectClient";
import HeaderAuth from "@/components/HeaderAuth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "URL Shortener",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignInUrl="/dashboard" afterSignUpUrl="/dashboard">
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground dark`}
        >
          <header className="flex justify-between items-center p-4 border-b bg-card text-card-foreground">
            <h1 className="text-2xl font-bold">URL Shortener</h1>
            <HeaderAuth />
          </header>
          <SignInRedirectClient />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
